const businessTestData = {
  paginatedBusinessResponse: {
    pageNumber: 1,
    totalPages: 1,
    pageSize: 10,
    totalCount: 1,
    lodgings: [
      {
        ownerid: 16,
        name: "American Dream Pizza",
        address: "2525 NW Monroe Ave.",
        city: "Corvallis",
        state: "OR",
        zip: "97330",
        phone: "541-757-1713",
        category: "Restaurant",
        subcategory: "Pizza",
        website: "http://adpizza.com",
        email: "brian@adpizza.com",
        reviews: [
          {
            userid: 7,
            businessid: 3,
            dollars: 3,
            stars: 5,
            review: "Great produce!",
          },
        ],
        photos: [
          {
            userid: 7,
            businessid: 3,
            caption: "Kale!",
          },
        ],
      },
    ],
  },
  sampleBusinessNoPhotosOrReviews: {
    ownerid: 16,
    name: "American Dream Pizza",
    address: "2525 NW Monroe Ave.",
    city: "Corvallis",
    state: "OR",
    zip: "97330",
    phone: "541-757-1713",
    category: "Restaurant",
    subcategory: "Pizza",
    website: "http://adpizza.com",
    email: "brian@adpizza.com",
  },
  sampleBusinessEdited: {
    ownerid: 16,
    name: "American Pizza",
    address: "9999 NW Monroe Ave.",
    city: "Corvallis",
    state: "OR",
    zip: "97999",
    phone: "999-999-1713",
    category: "Restaurant",
    subcategory: "Pizza",
    website: "http://adpizza.com",
    email: "brian@adpizza.com",
  },
  sampleBusinessWithReviewsPhotosEdited: {
    ownerid: 16,
    name: "American Pizza",
    address: "9999 NW Monroe Ave.",
    city: "Corvallis",
    state: "OR",
    zip: "97999",
    phone: "999-999-1713",
    category: "Restaurant",
    subcategory: "Pizza",
    website: "http://adpizza.com",
    email: "brian@adpizza.com",
    reviews: [
      {
        userid: 7,
        businessid: 3,
        dollars: 3,
        stars: 5,
        review: "Great produce!",
      },
    ],
    photos: [
      {
        userid: 7,
        businessid: 3,
        caption: "Kale!",
      },
    ],
  },

  sampleBusinessWithPhotosOrReviews: {
    ownerid: 16,
    name: "American Dream Pizza",
    address: "2525 NW Monroe Ave.",
    city: "Corvallis",
    state: "OR",
    zip: "97330",
    phone: "541-757-1713",
    category: "Restaurant",
    subcategory: "Pizza",
    website: "http://adpizza.com",
    email: "brian@adpizza.com",
    reviews: [
      {
        userid: 7,
        businessid: 3,
        dollars: 3,
        stars: 5,
        review: "Great produce!",
      },
    ],
    photos: [
      {
        userid: 7,
        businessid: 3,
        caption: "Kale!",
      },
    ],
  },
  sampleBusinessMissingData: {
    name: "American Dream Pizza",
    address: "2525 NW Monroe Ave.",
    state: "OR",
    zip: "97330",
    phone: "541-757-1713",
    category: "Restaurant",
  },
  sampleBusinessExpectedResponse: {
    id: 1,
  },
  sampleBusinessExpectedFailedResponse: {
    error: "string",
  },
};
